
package frc.robot.util;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj BumpAndBack = new ChoreoTraj(
	    "BumpAndBack",
	    OptionalInt.empty(),
	    6.38358,
	    new Pose2d(3.567, 0.862, Rotation2d.fromRadians(0)),
	    new Pose2d(1.747, 2.391, Rotation2d.fromRadians(0.785))
	);
	public static final ChoreoTraj GoOneMeter = new ChoreoTraj(
	    "GoOneMeter",
	    OptionalInt.empty(),
	    2.0504,
	    new Pose2d(3.55, 1.17, Rotation2d.fromRadians(0)),
	    new Pose2d(2.55, 1.17, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj OutpostTrajectory = new ChoreoTraj(
	    "OutpostTrajectory",
	    OptionalInt.empty(),
	    7.24499,
	    new Pose2d(3.583, 0.882, Rotation2d.fromRadians(0)),
	    new Pose2d(3.329, 3.978, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj OutpostTrajectory$0 = new ChoreoTraj(
	    "OutpostTrajectory",
	    OptionalInt.of(0),
	    1.7786,
	    new Pose2d(3.583, 0.882, Rotation2d.fromRadians(0)),
	    new Pose2d(3.312, 3.982, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj OutpostTrajectory$1 = new ChoreoTraj(
	    "OutpostTrajectory",
	    OptionalInt.of(1),
	    1.90393,
	    new Pose2d(3.312, 3.982, Rotation2d.fromRadians(0)),
	    new Pose2d(1.657, 0.67, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj OutpostTrajectory$2 = new ChoreoTraj(
	    "OutpostTrajectory",
	    OptionalInt.of(2),
	    3.5624599999999997,
	    new Pose2d(1.657, 0.67, Rotation2d.fromRadians(0)),
	    new Pose2d(3.329, 3.978, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj ClimbTestRoutine = new ChoreoTraj(
	    "ClimbTestRoutine",
	    OptionalInt.empty(),
	    7.22604,
	    new Pose2d(3.569, 0.872, Rotation2d.fromRadians(0)),
	    new Pose2d(1.36, 2.853, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj ClimbTestRoutine$0 = new ChoreoTraj(
	    "ClimbTestRoutine",
	    OptionalInt.of(0),
	    1.70793,
	    new Pose2d(3.569, 0.872, Rotation2d.fromRadians(0)),
	    new Pose2d(0.441, 0.661, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj ClimbTestRoutine$1 = new ChoreoTraj(
	    "ClimbTestRoutine",
	    OptionalInt.of(1),
	    1.5437999999999998,
	    new Pose2d(0.441, 0.661, Rotation2d.fromRadians(0)),
	    new Pose2d(2.643, 2.4, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj ClimbTestRoutine$2 = new ChoreoTraj(
	    "ClimbTestRoutine",
	    OptionalInt.of(2),
	    2.81612,
	    new Pose2d(2.643, 2.4, Rotation2d.fromRadians(0)),
	    new Pose2d(1.36, 2.4, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj ClimbTestRoutine$3 = new ChoreoTraj(
	    "ClimbTestRoutine",
	    OptionalInt.of(3),
	    1.1581900000000003,
	    new Pose2d(1.36, 2.4, Rotation2d.fromRadians(0)),
	    new Pose2d(1.36, 2.853, Rotation2d.fromRadians(0))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("BumpAndBack", BumpAndBack),
		Map.entry("GoOneMeter", GoOneMeter),
		Map.entry("OutpostTrajectory", OutpostTrajectory),
		Map.entry("OutpostTrajectory$0", OutpostTrajectory$0),
		Map.entry("OutpostTrajectory$1", OutpostTrajectory$1),
		Map.entry("OutpostTrajectory$2", OutpostTrajectory$2),
		Map.entry("ClimbTestRoutine", ClimbTestRoutine),
		Map.entry("ClimbTestRoutine$0", ClimbTestRoutine$0),
		Map.entry("ClimbTestRoutine$1", ClimbTestRoutine$1),
		Map.entry("ClimbTestRoutine$2", ClimbTestRoutine$2),
		Map.entry("ClimbTestRoutine$3", ClimbTestRoutine$3)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
