
package frc.robot.util;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj BumpAndBack = new ChoreoTraj(
	    "BumpAndBack",
	    OptionalInt.empty(),
	    7.27753,
	    new Pose2d(3.567, 0.862, Rotation2d.fromRadians(0)),
	    new Pose2d(1.747, 2.391, Rotation2d.fromRadians(0.785))
	);
	public static final ChoreoTraj ClimbTestRoutine = new ChoreoTraj(
	    "ClimbTestRoutine",
	    OptionalInt.empty(),
	    7.74331,
	    new Pose2d(3.569, 0.872, Rotation2d.fromRadians(0)),
	    new Pose2d(1.34, 2.981, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj ClimbTestRoutine$0 = new ChoreoTraj(
	    "ClimbTestRoutine",
	    OptionalInt.of(0),
	    5.62192,
	    new Pose2d(3.569, 0.872, Rotation2d.fromRadians(0)),
	    new Pose2d(1.34, 1.972, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj ClimbTestRoutine$1 = new ChoreoTraj(
	    "ClimbTestRoutine",
	    OptionalInt.of(1),
	    2.12139,
	    new Pose2d(1.34, 1.972, Rotation2d.fromRadians(0)),
	    new Pose2d(1.34, 2.981, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj GoOneMeter = new ChoreoTraj(
	    "GoOneMeter",
	    OptionalInt.empty(),
	    2.0504,
	    new Pose2d(3.55, 1.17, Rotation2d.fromRadians(0)),
	    new Pose2d(2.55, 1.17, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj OutpostTrajectory = new ChoreoTraj(
	    "OutpostTrajectory",
	    OptionalInt.empty(),
	    7.24499,
	    new Pose2d(3.583, 0.882, Rotation2d.fromRadians(0)),
	    new Pose2d(3.329, 3.978, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj OutpostTrajectory$0 = new ChoreoTraj(
	    "OutpostTrajectory",
	    OptionalInt.of(0),
	    1.7786,
	    new Pose2d(3.583, 0.882, Rotation2d.fromRadians(0)),
	    new Pose2d(3.312, 3.982, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj OutpostTrajectory$1 = new ChoreoTraj(
	    "OutpostTrajectory",
	    OptionalInt.of(1),
	    1.90393,
	    new Pose2d(3.312, 3.982, Rotation2d.fromRadians(0)),
	    new Pose2d(1.657, 0.67, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj OutpostTrajectory$2 = new ChoreoTraj(
	    "OutpostTrajectory",
	    OptionalInt.of(2),
	    3.5624599999999997,
	    new Pose2d(1.657, 0.67, Rotation2d.fromRadians(0)),
	    new Pose2d(3.329, 3.978, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj FullFieldPath = new ChoreoTraj(
	    "FullFieldPath",
	    OptionalInt.empty(),
	    17.44042,
	    new Pose2d(3.561, 0.874, Rotation2d.fromRadians(0)),
	    new Pose2d(3.469, 3.965, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj FullFieldPath$0 = new ChoreoTraj(
	    "FullFieldPath",
	    OptionalInt.of(0),
	    1.49045,
	    new Pose2d(3.561, 0.874, Rotation2d.fromRadians(0)),
	    new Pose2d(3.088, 2.451, Rotation2d.fromRadians(0.785))
	);
	public static final ChoreoTraj FullFieldPath$1 = new ChoreoTraj(
	    "FullFieldPath",
	    OptionalInt.of(1),
	    2.26471,
	    new Pose2d(3.088, 2.451, Rotation2d.fromRadians(0.785)),
	    new Pose2d(6.281, 2.408, Rotation2d.fromRadians(0.785))
	);
	public static final ChoreoTraj FullFieldPath$2 = new ChoreoTraj(
	    "FullFieldPath",
	    OptionalInt.of(2),
	    2.12617,
	    new Pose2d(6.281, 2.408, Rotation2d.fromRadians(0.785)),
	    new Pose2d(7.745, 0.726, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj FullFieldPath$3 = new ChoreoTraj(
	    "FullFieldPath",
	    OptionalInt.of(3),
	    5.0241299999999995,
	    new Pose2d(7.745, 0.726, Rotation2d.fromRadians(3.142)),
	    new Pose2d(7.779, 7.202, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj FullFieldPath$4 = new ChoreoTraj(
	    "FullFieldPath",
	    OptionalInt.of(4),
	    4.09821,
	    new Pose2d(7.779, 7.202, Rotation2d.fromRadians(3.142)),
	    new Pose2d(3.057, 5.53, Rotation2d.fromRadians(0.785))
	);
	public static final ChoreoTraj FullFieldPath$5 = new ChoreoTraj(
	    "FullFieldPath",
	    OptionalInt.of(5),
	    2.43675,
	    new Pose2d(3.057, 5.53, Rotation2d.fromRadians(0.785)),
	    new Pose2d(3.469, 3.965, Rotation2d.fromRadians(0))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("BumpAndBack", BumpAndBack),
		Map.entry("ClimbTestRoutine", ClimbTestRoutine),
		Map.entry("ClimbTestRoutine$0", ClimbTestRoutine$0),
		Map.entry("ClimbTestRoutine$1", ClimbTestRoutine$1),
		Map.entry("GoOneMeter", GoOneMeter),
		Map.entry("OutpostTrajectory", OutpostTrajectory),
		Map.entry("OutpostTrajectory$0", OutpostTrajectory$0),
		Map.entry("OutpostTrajectory$1", OutpostTrajectory$1),
		Map.entry("OutpostTrajectory$2", OutpostTrajectory$2),
		Map.entry("FullFieldPath", FullFieldPath),
		Map.entry("FullFieldPath$0", FullFieldPath$0),
		Map.entry("FullFieldPath$1", FullFieldPath$1),
		Map.entry("FullFieldPath$2", FullFieldPath$2),
		Map.entry("FullFieldPath$3", FullFieldPath$3),
		Map.entry("FullFieldPath$4", FullFieldPath$4),
		Map.entry("FullFieldPath$5", FullFieldPath$5)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
